import Foundation
import CoreGraphics
// Lifecycle checks without posting keyboard events or requiring a controller.
var hold = HoldState<String, Int>()
precondition(hold.end() == nil)
precondition(hold.begin(owner: "controller-A", destination: 101))
precondition(!hold.begin(owner: "controller-A", destination: 202))
precondition(!hold.begin(owner: "controller-B", destination: 202))
precondition(hold.end(owner: "controller-B") == nil)
precondition(hold.active?.destination == 101)
precondition(hold.end(owner: "controller-A") == 101)
precondition(hold.end(owner: "controller-A") == nil)
// Pause, disconnect, quit and focus loss use the unconditional cleanup path.
precondition(hold.begin(owner: "controller-A", destination: 303))
precondition(hold.end() == 303)
precondition(hold.end() == nil)
precondition(hold.begin(owner: "controller-B", destination: 404))
precondition(hold.end(owner: "controller-B") == 404)
print("Hold lifecycle passed: one press/release, owner isolation, original target, cleanup and reconnect.")

var trigger = TriggerGesture()
precondition(trigger.update(1, allowed: true) == nil) // Connected while held: no send.
precondition(trigger.update(0, allowed: true) == nil)
precondition(trigger.update(0.12, allowed: true) == nil)
precondition(trigger.update(0, allowed: true) == nil) // Ignore resting noise.
precondition(trigger.update(0.4, allowed: true) == nil)
precondition(trigger.update(0.1, allowed: true) == nil)
precondition(trigger.update(0, allowed: true) == .queue)
precondition(trigger.update(0, allowed: true) == nil)
precondition(trigger.update(0.3, allowed: true) == nil)
precondition(trigger.update(0.85, allowed: true) == .immediate)
precondition(trigger.update(0.7, allowed: true) == nil)
precondition(trigger.update(1, allowed: true) == nil)
precondition(trigger.update(0, allowed: true) == nil) // No queue after deep press.
precondition(trigger.update(0.5, allowed: true) == nil)
precondition(trigger.update(0.5, allowed: false) == nil)
precondition(trigger.update(1, allowed: true) == nil) // Focus restored while held.
precondition(trigger.update(0, allowed: true) == nil)
precondition(trigger.update(0.3, allowed: true) == nil)
trigger.cancel()
precondition(trigger.update(0, allowed: true) == nil)
precondition(trigger.update(1, allowed: true) == .immediate)
print("R2 passed: light release, deep press, jitter, one send per squeeze, cancellation and rearming.")

precondition(StickNavigation.mode(roles: ["AXTextArea", "AXList", "AXWebArea"], openedWithOptions: false) == .content)
precondition(StickNavigation.mode(roles: ["AXTextArea", "AXWebArea"], openedWithOptions: true) == .content)
precondition(StickNavigation.mode(roles: ["AXTextField", "AXGroup"], openedWithOptions: false) == .content)
precondition(StickNavigation.mode(roles: ["AXTextField", "AXGroup"], openedWithOptions: true) == .menu)
precondition(StickNavigation.mode(roles: ["AXMenuItem", "AXMenu"], openedWithOptions: false) == .menu)
precondition(StickNavigation.mode(roles: ["AXTextField", "AXDialog"], openedWithOptions: false) == .menu)
precondition(StickNavigation.mode(roles: ["AXComboBox", "AXWebArea"], openedWithOptions: false) == .content)
print("Stick routing passed: focused composer, stale menu state, list ancestors, actual menus and dialogs.")

let window = CGRect(x: 0, y: 0, width: 1600, height: 1000)
let closed = CGRect(x: 350, y: 800, width: 900, height: 120)
let sidebarOpen = CGRect(x: 680, y: 800, width: 700, height: 120)
let rightPanelOpen = CGRect(x: 280, y: 800, width: 620, height: 120)
precondition(ConversationGeometry.scrollPoint(composer: closed, window: window)?.x == 800)
precondition(ConversationGeometry.scrollPoint(composer: sidebarOpen, window: window)?.x == 1030)
precondition(ConversationGeometry.scrollPoint(composer: rightPanelOpen, window: window)?.x == 590)
precondition(ConversationGeometry.scrollPoint(composer: rightPanelOpen, window: window)!.y < rightPanelOpen.minY)
let movedWindow = window.offsetBy(dx: -1800, dy: 200)
let movedInput = rightPanelOpen.offsetBy(dx: -1800, dy: 200)
precondition(ConversationGeometry.scrollPoint(composer: movedInput, window: movedWindow)?.x == -1210)
precondition(ConversationGeometry.scrollPoint(composer: CGRect(x: 20, y: 90, width: 200, height: 28), window: window) == nil)
precondition(ConversationGeometry.scrollPoint(composer: CGRect(x: 400, y: 100, width: 900, height: 850), window: window) == nil)
precondition(ConversationGeometry.scrollPoint(composer: closed.offsetBy(dx: 2000, dy: 0), window: window) == nil)
precondition(StickNavigation.mode(roles: ["AXOutline", "AXScrollArea"], openedWithOptions: false) == .content)
print("Conversation targeting passed: left sidebar, right panel, moved window, sidebar search, full-height editor and offscreen fields.")
